#!/bin/bash

install() {
	go get
}

test() {
	go test \
		klog/parser \
		klog/workday \
		klog/store \
		klog/serialiser \
		klog/datetime
}

format() {
	go fmt workday/*
	go fmt parser/*
	go fmt store/*
	go fmt serialiser/*
	go fmt datetime/*
}

cli() {
	go run cli/main.go $@
}

$1 ${@:2}
