#!/bin/sh

install() {
	go get -t ./...
}

build() {
	go build \
	  -ldflags "-X 'github.com/jotaen/klog/src/app.BinaryVersion=$1' -X 'github.com/jotaen/klog/src/app.BinaryBuildHash=$2'" \
	  -o ./out/klog \
	  src/app/main/klog.go
}

test() {
	go test ./...
}

format() {
	go fmt ./...
}

cli() {
	go run src/app/main/klog.go "$@"
}

# MAIN
task=$1
shift 1
$task "$@"
